// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRdxDffmsi6hNQ9EU1vsKI8Jf6Jrg62M',
    appId: '1:685566921004:web:f0bf58b3cc5ef824330489',
    messagingSenderId: '685566921004',
    projectId: 'calendar-schedule-54c01',
    authDomain: 'calendar-schedule-54c01.firebaseapp.com',
    storageBucket: 'calendar-schedule-54c01.appspot.com',
    measurementId: 'G-KVH11Y59RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWVICqiAmyBVoVaiAm2mwPxFOkB6TKk8',
    appId: '1:685566921004:android:f8a26cdd1f0a86af330489',
    messagingSenderId: '685566921004',
    projectId: 'calendar-schedule-54c01',
    storageBucket: 'calendar-schedule-54c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdy6rbstNo_ySJGIgeLgONtK_7aUzAFU',
    appId: '1:685566921004:ios:409fcc4b2ee9c7ed330489',
    messagingSenderId: '685566921004',
    projectId: 'calendar-schedule-54c01',
    storageBucket: 'calendar-schedule-54c01.appspot.com',
    iosBundleId: 'com.example.scheduleCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdy6rbstNo_ySJGIgeLgONtK_7aUzAFU',
    appId: '1:685566921004:ios:20329792454e5431330489',
    messagingSenderId: '685566921004',
    projectId: 'calendar-schedule-54c01',
    storageBucket: 'calendar-schedule-54c01.appspot.com',
    iosBundleId: 'com.example.scheduleCalendar.RunnerTests',
  );
}
